//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orderProducts = new HashSet<orderProduct>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string descrip { get; set; }
        public string img { get; set; }
        public Nullable<int> stock { get; set; }
        public string brand { get; set; }
        public Nullable<int> catId { get; set; }
        public Nullable<int> supId { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> adminId { get; set; }
    
        public virtual Adminstrator Adminstrator { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderProduct> orderProducts { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
