//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTbl()
        {
            this.orderTbls = new HashSet<orderTbl>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string passwrd { get; set; }
        public Nullable<int> cardNumber { get; set; }
        public Nullable<int> phone { get; set; }
        public string addres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTbl> orderTbls { get; set; }
    }
}
